language: node_js

node_js:
  - lts/*

install:
  - npm ci

script:
  - npm run docs:build

deploy:
  provider: pages
  repo: cireu/cireu.github.io
  branch: master
  skip-cleanup: true
  local_dir: docs/.vuepress/dist
  github-token: $GH_TOKEN
  keep-history: true
  on:
    branch: master
